#!/bin/sh

if ! python3 TMP/xxx.py >TMP/xxx-py.txt
then
        cat TMP/xxx-py.txt
        exit 1
fi

ls -ls TMP/xxx.py TMP/StoX.js

node TMP/StoX.js >TMP/xxx-js.txt

if cmp TMP/xxx-py.txt TMP/xxx-js.txt
then
        echo "JavaScript output the same thing than Python"
else
        diff -u TMP/xxx-py.txt TMP/xxx-js.txt
fi









