#!/bin/sh

if ! python3 xxx.py >xxx-py.txt
then
        cat xxx-py.txt
        exit 1
fi

ls -ls xxx.py xxx.js

node xxx.js >xxx-js.txt

if cmp xxx-py.txt xxx-js.txt
then
        echo "JavaScript output the same thing than Python"
else
        diff -u xxx-py.txt xxx-js.txt
fi









