#!/bin/sh

if [ ! -x RapydScript/bin/rapydscript ]
then
        git clone https://github.com/atsepkov/RapydScript.git
fi

RapydScript/bin/rapydscript --prettify --bare xxx.py |
sed -e 's/x.__class__.__name__/typeof(x)/'  >xxx.js

python3 xxx.py >xxx-py.txt || exit 1


ls -ls xxx.py xxx.js

node xxx.js >xxx-js.txt

if cmp xxx-py.txt xxx-js.txt
then
        echo "JavaScript output the same thing than Python"
else
        diff -u xxx-py.txt xxx-js.txt
fi









